# Generated by Django 4.2.16 on 2024-09-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('A', 'Adventure'), ('F', 'Family'), ('E', 'Fighting'), ('L', 'Life Sim'), ('M', 'Racing'), ('R', 'RPG'), ('S', 'Shooter'), ('T', 'Sports')], default='A', max_length=1)),
                ('status', models.CharField(choices=[('U', 'Unstarted'), ('P', 'Playing'), ('B', 'Break'), ('F', 'Finished')], default='U', max_length=1)),
            ],
        ),
    ]
