# Generated by Django 4.2.16 on 2024-09-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_game_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('A', 'Action/ Adventure'), ('F', 'Family'), ('FI', 'Fighting'), ('LS', 'Life Sim'), ('MM', 'MMO/ MOBA'), ('P', 'Platformer'), ('R', 'Racing'), ('RPG', 'RPG'), ('S', 'Shooter'), ('SP', 'Sports'), ('ST', 'Stealth')], default='A', max_length=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('U', 'Unstarted'), ('P', 'Playing'), ('B', 'Taking a Break'), ('F', 'Finished')], default='U', max_length=1),
        ),
    ]
